name: basic_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  path_provider: ^2.1.1
  flutter:
    sdk: flutter 
  intl: ^0.18.1
  connectivity_plus: ^4.0.0
  http: ^1.3.0
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.9.0


dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0